### ISSUE TITLE
FileNotFound when running 'setup.py'

### ISSUE THREAD

**Issue by Red-edge** [clearlab-sustech/Wheel-Legged-Gym#1]
I was running on 'python wheel_legged_gym/scripts/play.py --task=wheel_legged_vmc_flat' but feedback was 'FileNotFoundError: [Errno 2] No such file or directory: '/home/AAA/Downloads/Wheel-Legged-Gym/logs/wheel_legged_vmc_flat''

**Comment by Red-edge** [comment]
solved sry :)

**Comment by SnoopyGeeek** [comment]
How did you solve the problem? I met the same issue.

**Comment by Red-edge** [comment]
> How did you solve the problem? I met the same issue.

The file indeed not contained wheel_legged_vmc_flat folder

but the directory contain usable folders

whats more, you must create a training folder with specific name manually to contain the output of training, check out the error output
